# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dasa Sathyan @ javadas
tagline:          Senior Software Consultant, Platformatory
description:      'Full stack Developer with a DevOps flavour, Historyphile, Backpacker and a lot more. '
# url:              https://dasasathyan.github.io/personal-blog/
# base_url:         /personal-blog

# About/contact
author:
  name:              Dasa Sathyan
  url:               https://twitter.com/dasasathyan
  email:             dasasathyan@gmail.com

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false
