# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dasa Sathyan @ javadas
tagline:          'Accountant turned Developer'
description:      'Here, I share with what I play in technology, what I explore in history, how I have fun'
url:              https://dasasathyan.github.io/personal-blog/

# About/contact
author:
  name:              Dasa Sathyan
  url:               https://twitter.com/dasasathyan
  email:             dasasathyan@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
