# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dasa Sathyan @ javadas
tagline:          Senior Software Consultant, Platformatory
description:      'Full stack Developer with a DevOps flavour, Historyphile, wanderlust and a lot more. '
url:              https://dasasathyan.github.io/personal-blog/

# About/contact
author:
  name:              Dasa Sathyan
  url:               https://twitter.com/dasasathyan
  email:             dasasathyan@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
